services:
  datagenerator:
    build: ./dataGenerator
    environment:
      - PYTHONUNBUFFERED=1 #Immediate console output
      - HOST=host.docker.internal #subject to change
      - PORT=5000
      - DATA_MIN=1
      - DATA_MAX=100
      - INTERVAL=2
    deploy:
      replicas: 4